#!/bin/bash
yum install wget -y
yum install net-tools -y
sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo --no-check-certificate
rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
yum upgrade -y
yum install fontconfig java-17-openjdk -y
yum install jenkins -y
systemctl enable jenkins
systemctl restart jenkins
firewall-cmd --list-all
firewall-cmd --add-port=8080/tcp --permanent
firewall-cmd --reload
which jenkins
which java
jenkins --version
