#!/bin/bash

hosts=($(<sampleip.txt))

read -p "Enter username: " new_user
read -s -p "Enter password: " new_password

for host in "${hosts[@]}"; do
    # SSH and create user on remote server
    ssh "$host" "sudo useradd $new_user && echo '$new_user:$new_password' | sudo chpasswd"

    echo "User $new_user created on $host and password is set"
done
